### ISSUE TITLE
NSInternalInconsistencyException while recording a snapshot with DynamicType.

### ISSUE THREAD

**Issue by Lewion** [ashfurrow/Nimble-Snapshots#103]
The following issue arises when I try to use DynamicType snapshots. 
The issue occurs with or without passing each parameter to the method and with both the record and validation methods.

<img width="616" alt="screen shot 2017-05-24 at 10 21 00" src="https://cloud.githubusercontent.com/assets/445154/26393704/eba417d8-406a-11e7-89ff-2a4e86c9e126.png">

Any ideas on how to fix this issue? I have already updated all required pods to the latest version.

**Comment by Lewion** [comment]
The issue was to provide a valid Host Application to be able to test Dynamic Type. NBSMockApplication would otherwise crash on a nil value for UIApplication.

I have sent a pull request to update the README accordingly: https://github.com/ashfurrow/Nimble-Snapshots/pull/104

**Comment by marcelofabri** [comment]
Closing this since #104 was merged 🎉
