### ISSUE TITLE
Can't make Nimble-Snapshots to apply UIAppearance during tests

### ISSUE THREAD

**Issue by jgongo** [ashfurrow/Nimble-Snapshots#109]
I've been trying to test that my views behave correctly using `UIAppearance` but I haven't been able to make `Nimble-Snapshots` apply my configured `UIAppearance` attributes during the test. After taking a look at both the code of `ios-snapshot-test-case` and `Nimble-Snapshots` it seems this should be supported according to this [pull request](https://github.com/facebook/ios-snapshot-test-case/pull/100) and using the `usesDrawRect` parameter in `recordSnapshot`. 

Here you have a failing test case:

```
import UIKit
import Quick
import Nimble
import Nimble_Snapshots


class SnapshotSpec: QuickSpec {
    override func spec() {
        describe("Appearance snapshots") {
            it("should work") {
                UILabel.appearance().textColor = UIColor.blue
                UILabel.appearance().font = UIFont.boldSystemFont(ofSize: 20)
                
                let label = UILabel(frame: CGRect(x: 0, y: 0, width: 200, height: 50))
                label.text = "This should be big & blue"
                
                expect(label).to(recordSnapshot(named: "label", usesDrawRect: true))
            }
        }
    }
}
```

The label in the recorded snapshot uses default attributes instead of the attributes configured using the `UIAppearance` proxy. Am I missing anything?

**Comment by marcelofabri** [comment]
This [should work](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/Bootstrap/BootstrapTests/BootstrapTests.swift#L45-L50). Maybe these properties don't support `UIApperance`?

**Comment by jgongo** [comment]
Ok, ignore this, sorry for the noise. My tests weren't working and I don't know why. When I have re-created them they work.

**Comment by marcelofabri** [comment]
Cool, glad you've figured it out! 👍
