### ISSUE TITLE
Nimble-Snapshots does not work properly if UIApperance attributes change intrinsic content size of view being tested

### ISSUE THREAD

**Issue by jgongo** [ashfurrow/Nimble-Snapshots#110]
I'm having a problem regarding a view that isn't being properly recorded when I change an attribute of the view using the UIAppearance proxy, if that attribute would change the intrinsic content size of the view. In this case, the image is clipped to the original size of the view.

This seems to be caused by [a bug in ios-snapshot-test-case](https://github.com/facebook/ios-snapshot-test-case/issues/227).

**Comment by jgongo** [comment]
I have noticed this also happens when setting a property that changes the intrinsic content size (for example, setting a large text)

**Comment by ashfurrow** [comment]
Interesting, can you expand? What does the failing test code look like?

**Comment by jgongo** [comment]
I've added a [comment in the ios-snapshot-test-case bug](https://github.com/facebook/ios-snapshot-test-case/issues/227#issuecomment-305099314) with a test case and a bit of explanation

**Comment by jgongo** [comment]
And a [pull request](https://github.com/facebook/ios-snapshot-test-case/pull/228) ;)

**Comment by ashfurrow** [comment]
Okay, sounds good 👍 Just let me know what we can to do help.

**Comment by Vkt0r** [comment]
@ashfurrow I think with #147 and the update of the version of the library Uber fixed this issue in the latest version according to its [CHANGELOG](https://github.com/uber/ios-snapshot-test-case/blob/master/CHANGELOG.md). 

@jgongo Could you validate if the bug is happening using the latest version of the ios-snapshot-test-case library?

**Comment by Vkt0r** [comment]
This can be closed as it was solved in #147. @jgongo Please reopen it in case it comes back (I hope not 🤞)
