### ISSUE TITLE
Build Failed with exit code 65 - Installation via Carthage

### ISSUE THREAD

**Issue by alextakahashi** [ashfurrow/Nimble-Snapshots#111]
I tried integrating Nimble-Snapshots into my project using Carthage, but I am running into an error during installation.

**Terminal Error**
```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /foo/Carthage/Checkouts/Nimble-Snapshots/Nimble_Snapshots.xcodeproj -scheme Nimble_Snapshots -configuration Release -derivedDataPath /bar/Caches/org.carthage.CarthageKit/DerivedData/Nimble-Snapshots/5.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/qb/82lnd6t96l5f72_jtzrkzd_4xd0_fn/T/carthage-xcodebuild.FYHRJ7.log
```

Inside the log

**Xcode build log**
```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /baz/Carthage/Checkouts/Nimble-Snapshots/DynamicType/HaveValidDynamicTypeSnapshot.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

For now I am using Cocoapods and it seems to work fine, but I'd rather use Carthage if possible.  

**Notes**
* I am not sure if this is a Carthage problem or a Nimble-Snapshots problem
* Other sources I've tried:
    * [Build Failed with exit code 65](https://github.com/Carthage/Carthage/issues/1538)
    * [Carthage update - Task failed with exit code 65](https://stackoverflow.com/questions/43831086/carthage-update-task-failed-with-exit-code-65)

**Comment by sstadelman** [comment]
Which phase is failing, of the 'installation'. Does `carthage update` fail to complete?  Or is the failure occurring when compiling the test target?

**Comment by alextakahashi** [comment]
`carthage update` fails.  

The failure is occurring during 

```
=== BUILD TARGET Nimble_Snapshots OF PROJECT Nimble_Snapshots WITH CONFIGURATION Release ===
```

Looking deeper into my build log, it is failing here

```
/foo/Carthage/Checkouts/Nimble-Snapshots/DynamicType/HaveValidDynamicTypeSnapshot.swift:42:16: error: use of unresolved identifier 'NBSMockedApplication'
    let mock = NBSMockedApplication()
               ^~~~~~~~~~~~~~~~~~~~
/foo/Carthage/Checkouts/Nimble-Snapshots/DynamicType/HaveValidDynamicTypeSnapshot.swift:71:16: error: use of unresolved identifier 'NBSMockedApplication'
    let mock = NBSMockedApplication()
               ^~~~~~~~~~~~~~~~~~~~
```
[DynamicTypeSnapshot.swift Reference](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/DynamicType/HaveValidDynamicTypeSnapshot.swift)

I'm not sure why the `NBSMockedApplication()` cant be recognized...

**Comment by marcelofabri** [comment]
What version are you trying to run? One of them was broken with Carthage (sorry!), but the latest one should be fine. Also [deleting its cache](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/Rakefile#L15) may help.

**Comment by marcelofabri** [comment]
I think `5.1.0` is the broken one.

**Comment by alextakahashi** [comment]
Yup, I was running the older broken version `5.1.0`! Glad it's working out now.

I was following the `README.md`exactly and my Cartfile had:
```
github "Quick/Quick" ~> 1.0
github "Quick/Nimble" ~> 7.0
github "facebook/ios-snapshot-test-case" "2.1.4"
github "ashfurrow/Nimble-Snapshots"  ~> 5.0
```
Yup just changed it to and no errors! 🙌
```
github "ashfurrow/Nimble-Snapshots"
```

Just created a pull request

**Comment by marcelofabri** [comment]
@alextakahashi thanks for the feedback and updating the README. Sorry for all the trouble 😬
