### ISSUE TITLE
Tests failing from command line

### ISSUE THREAD

**Issue by NachoSoto** [ashfurrow/Nimble-Snapshots#120]
So I got several tests now working and passing from Xcode, but when running them from the command line, they fail with a cryptic error:
```
Test Case '-[...]' started.
Spec.swift:41: error: -[...] : , got expected a matching snapshot in {snapshot_name}
```

It's not clear whether it's not finding the snapshots (which are there), they're mismatching, or what. Looks like even the expectation error is malformed: `, got expected a matching snapshot in {snapshot_name}`.

**Comment by marcelofabri** [comment]
Just to be sure: are you using the same simulator on Xcode and the command line?

This error would happen if you're using a `@2x` and `@3x` devices, for example.

**Comment by ashfurrow** [comment]
Usually if there's a difference in the snapshots, you'll get a `ksdiff` command to invoke. This error, as @marcelofabri is when it can't find a snapshot to compare _to_.

**Comment by NachoSoto** [comment]
Thanks, that was totally it :) I added an assertion like in the test project to prevent this in the future 👍

**Comment by NachoSoto** [comment]
Unrelated issue, but I'll ask here first: for some reason colors are slightly different when running tests on iOS 9.x versus 10.x... have any of you seen that before?

**Comment by NachoSoto** [comment]
Never mind, this is the issue: https://github.com/facebook/ios-snapshot-test-case/issues/184.
