### ISSUE TITLE
Fail during carthage update

### ISSUE THREAD

**Issue by rodriguv** [ashfurrow/Nimble-Snapshots#121]
/Users/rodriguv/Desktop/PlayPlex-iOS/Carthage/Checkouts/Nimble-
    Snapshots/DynamicSize/DynamicSizeSnapshot.swift:141:78:` error: use of undeclared type 
        'Predicate'
                                        resizeMode: ResizeMode = .frame) -> Predicate<Snapshotable> {
                                                                             ^~~~~~~~~
    /Users/rodriguv/Desktop/PlayPlex-iOS/Carthage/Checkouts/Nimble-
    Snapshots/HaveValidSnapshot.swift:224:86: error: use of undeclared type 'Predicate'
    public func recordSnapshot(named name: String? = nil, usesDrawRect: Bool = false) -> 
    Predicate<Snapshotable> {
                                                                               ^~~~~~~~~
    /Users/rodriguv/Desktop/PlayPlex-iOS/Carthage/Checkouts/Nimble-
    Snapshots/DynamicSize/DynamicSizeSnapshot.swift:203:75: error: use of undeclared type 
    'Predicate'
                                      resizeMode: ResizeMode = .frame) -> Predicate<Snapshotable> {
                                                                           ^~~~~~~~~

    ** BUILD FAILED **

Does anyone know what's going on here? Is there a bug that needs to be fixed. I keep getting this error of undeclared type 'Predicate'

**Comment by ashfurrow** [comment]
Usually this happens with older versions of Nimble. Could you try updating Nimble and see if that fixes it?

**Comment by rodriguv** [comment]
Yes! My apologies! I tried the Nimble version of 7.0 as seen in your README and that worked! Thanks!

**Comment by ashfurrow** [comment]
Glad it's working!
