### ISSUE TITLE
How to load the view controller before recording/validating a snapshot

### ISSUE THREAD

**Issue by fabiomassimo** [ashfurrow/Nimble-Snapshots#124]
I have seen different approaches on how the view controller, that needs to be "snapshot-ed", is loaded before the recording/validating session.

At Artsy they are using following extension over `UIViewController`:

```swift
extension UIViewController {
    /// Short hand syntax for loading the view controller
    func loadViewProgrammatically(){
        self.beginAppearanceTransition(true, animated: false)
        self.endAppearanceTransition()
    }
}
```

Although, for me the **only** way to make it work is to initialise the view controller and manually assign it as the root view controller of the `UIApplication.shared` window (wrong?)

```swift
extension UIApplication {
    func setRootViewController(_ viewController: UIViewController) {
        delegate!.window!!.rootViewController = viewController
    }
}

class MyViewControllerSnapshotTests: QuickSpec {
    override func spec() {
        describe("Something that") {
            it("has valid snapshot") {
                let viewModel = MyViewModel()
                let viewController = MyViewController(viewModel: viewModel)
                UIApplication.shared.setRootViewController(viewController)
                
                expect(viewController).to(recordSnapshot())
            }
        }
    }
}

```

I don't like it as a solution and I was wondering if anyone can share how he got around it and ideally why the Artsy solution is not working for me :(

**Comment by ashfurrow** [comment]
That's odd, you shouldn't have to do that. What kind of behaviour/error are you seeing otherwise?

**Comment by fabiomassimo** [comment]
I'm very sorry. I do not know what to say or what actually happened.
Same project, same code just launched it after a reboot of my MacBook (for other related things) and now it works. 

Thank you again for your time.
If anyone is having this issue I confirm that the Artsy approach works great.
