### ISSUE TITLE
Xcode 9 beta 5 compile error

### ISSUE THREAD

**Issue by spekke** [ashfurrow/Nimble-Snapshots#131]
I get the following compile error in CurrentTestCaseTracker.swift when using Xcode 9 beta 5:

![nimble_snapshot](https://user-images.githubusercontent.com/604657/29064400-1e03a3e8-7c29-11e7-85cd-e062056ca802.png)

I'm happy to help out with a PR. Any ideas how to solve this so it works with "all" versions of Xcode?

**Comment by marcelofabri** [comment]
There's an [xcode9-beta](https://github.com/ashfurrow/Nimble-Snapshots/tree/xcode9-beta) branch that should work.

**Comment by spekke** [comment]
Cool thanks!
