### ISSUE TITLE
Snapshot file location defined within `it` not used in 5.0.0+

### ISSUE THREAD

**Issue by aarons22** [ashfurrow/Nimble-Snapshots#135]
When defining a custom file location for a Quick test, the file location seems to be ignored for snapshot tests:

```
class QuickLayoutSpec: QuickSpec {
   func checkSnapshot(file: String) {
      it("has correct snapshot", file: "\(file)") {
         expect(view).to(recordSnapshot())
      }
   }
}
```

```
class ViewTest: QuickLayoutSpec {
   override func spec() {
      describe("myTest") {
         self.checkSnapshot(file: "ViewTest")
      }
   }
}
```

The file structure being used:
```
- Views
-- ViewTest.swift (extends QuickLayoutSpec)
- TestClassExtensions
-- QuickLayoutSpec.swift
```

So when the test is run, the snapshots are placed in `ReferenceImages/QuickLayoutSpec` instead of `ReferenceImages/ViewTest`, which is the behavior in Nimble-Snapshots v4.4.2

**Comment by ashfurrow** [comment]
Yikes, this is a tricky one. I've never heard of subclassing specs like that, I'm not surprised the behaviour broke between major versions. Hmm. I'll have a think and see if I can come up with a workaround or something. @marcelofabri any ideas?

**Comment by marcelofabri** [comment]
We get the file from the Nimble expression (`recordSnapshot`) for example. If it's inside a base class, it'll use that file instead.

This is where we do that: https://github.com/ashfurrow/Nimble-Snapshots/blob/master/HaveValidSnapshot.swift#L142-L143

I'm not sure how easy would it be to fix this.

**Comment by orta** [comment]
If it can be detected, it might just be worth bailing and telling someone to use `named:`

**Comment by aarons22** [comment]
One option would be to provide a output directory option to `recordSnapshot ` and `haveValidSnapshot`. This could also be built into named (e.g. `directory_path/name`)

**Comment by ashfurrow** [comment]
Adding the directory name params to `record/haveValidSnapshot()` is definitely doable. I feel like that that breaks the abstraction of snapshot names a bit, I'm not totally sold on the idea. Hmm. 

What if you moved the `checkSnapshot()` function outside the `QuickLayoutSpec` class? Put it in the global scope? You'd have to remove `self.` when calling it, but then the `ViewTest` class should be the "current test class name" detection might work. Not sure, worth a shot though. Can you try and let us know?

**Comment by aarons22** [comment]
I'll give it a shot!

**Comment by aarons22** [comment]
Alright, I tried this out, but it still used the name of the file that the global method is in.

**Comment by ashfurrow** [comment]
Okay, hmm. Having an intermediate subclass of `QuickSpec` is a fairly unusual use case of Quick, and adding a new parameter really breaks the abstraction that this library builds up. I don't think this is a use case I want to build support for, but I encourage you to fork the library develop this. If you have any questions about that process, I'd be happy to help.

**Comment by aarons22** [comment]
Wanted to follow up on this issue with a solution I came up with. I'm passing the `FileString` reference from the original file so the `expect` has the correct path for the image:

```
class QuickLayoutSpec: QuickSpec {
   func checkSnapshot(file: FileString) {
      it("has correct snapshot") {
         expect(view, file: file).to(recordSnapshot())
      }
   }
}
```

```
class ViewTest: QuickLayoutSpec {
   override func spec() {
      describe("myTest") {
         self.checkSnapshot(file: #file)
      }
   }
}
```

It was right in front of me the entire time :)

**Comment by ashfurrow** [comment]
Awesome! I'm glad you found a solution – and thank you for sharing it. I'm sure it'll help some lost soul who finds this issue through a frantic Google search 😄
