### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by NachoSoto** [ashfurrow/Nimble-Snapshots#139]
I ran into https://github.com/skyweb07/Snap.swift and noticed that the test results contain attachments with the reference and actual images. I haven't done any research on how it's doing that, but it would be awesome to do that in `Nimble-Snapshots` too :D

![Image](https://github.com/skyweb07/Snap.swift/raw/develop/.art/xcode_attachment.png)

**Comment by ashfurrow** [comment]
Totally! We rely on [FBSnapshotTestCase](https://github.com/facebookarchive/ios-snapshot-test-case) under the hood, which supports something similar via the `IMAGE_DIFF_DIR` environment variable. There's also [second_curtain](https://github.com/ashfurrow/second_curtain) if you're running on a CI environment. 

That said, there may be ways we can extend or modifying this library's behaviour to better suit needs. If anyone has any input, chime in 🔔

**Comment by skyweb07** [comment]
Hey @ashfurrow it's a super simple API from the new XCTests, here's how I'm doing right now on `Snap.swift` https://github.com/skyweb07/Snap.swift/blob/develop/Snap/Core/Application/Actions/AddAttachment.swift, it also has an initializer for passing URL of the file so you won't have to depend on `FBSnapshotTestCase`

**Comment by ashfurrow** [comment]
Cool! Sounds like something we should probably integrate with. Unfortunately, I don't have the availability to work on this right now. I'll try to circle back in a few weeks.

**Comment by orta** [comment]
Or someone else can PR it in the meantime

**Comment by tsabend** [comment]
closed by #156
