### ISSUE TITLE
Migrate to iOSSnapshotTestCase

### ISSUE THREAD

**Issue by marcelofabri** [ashfurrow/Nimble-Snapshots#141]
Uber is now the official maintainer of [iOSSnapshotTestCase](https://github.com/uber/ios-snapshot-test-case), previously `FBSnapshotTestCase`. We probably should start using their repo as a dependency.

**Comment by ashfurrow** [comment]
Agreed. #142 has been opened for this.

**Comment by ejmartin504** [comment]
Howdy @ashfurrow! I believe this is closed after the merge of #144

**Comment by marcelofabri** [comment]
🎉

**Comment by ejmartin504** [comment]
@marcelofabri any chance of getting a release with this change?

**Comment by marcelofabri** [comment]
I think it deserves a release. @ashfurrow should we make it 7.0.0 because of the dependency change?

**Comment by ashfurrow** [comment]
Yeah sounds good 👍 Thanks!
