### ISSUE TITLE
Weird conditional

### ISSUE THREAD

**Issue by davertay** [ashfurrow/Nimble-Snapshots#145]
Is this a typo where the second condition is meant to be `height` instead of `width`?
https://github.com/ashfurrow/Nimble-Snapshots/blob/master/DynamicSize/DynamicSizeSnapshot.swift#L71

Updating this with a secondary query. A few lines before this `layoutIfNeeded()` is called, however as `setNeedsLayout()` is not called first it is almost guaranteed that the conditional `view.bounds.width != size.width` will fail.

So then my question really changes to: can this entire "iOS 9+ BUG" hack be avoided by tripping the `setNeedsLayout()` flag instead?

**Comment by ashfurrow** [comment]
Hmm, good question. I think it is a typo, but I'm not sure about the rest. @marcelofabri what do you think?

**Comment by marcelofabri** [comment]
This looks weird in fact. I think it should be `height`. Maybe @BrunoMazzo can give some insights for the whole "iOS 9+ BUG" section too as he was the original author?

**Comment by Vkt0r** [comment]
I think we can close this as #145 solved
