### ISSUE TITLE
Device or screen size based assertion

### ISSUE THREAD

**Issue by ryancrosby** [ashfurrow/Nimble-Snapshots#15]
This framework is great, but for some view assertions they don't work across devices. I would like to have a haveValidScreenRatioDependentSnapshot(), that would generate a file name using the an aspect ratio, device type, or screensize. Not exactly sure on the naming or how best to implement this. This would make Xcode Continuous Integrations tests pass better when using a screen snapshot or full width or height snapshot, since it can test on all devices.

I haven't looked into what the facebook library provides yet, but wanted to bring this up as a potential feature in the meantime. Any thoughts?

**Comment by orta** [comment]
There is talk about moving that into FBSnapshot, but I think there's definitely some value here. I think I would prefer this in. 

It's really that we both test differently, we use the same sim and mock devices and you use real devices/sims. I wonder if there's a syntactical change or a settings thing that can trigger different behaviors. 

Or we just deal with it and say that your @ryancrosby changes provide a better experience regardless.

**Comment by orta** [comment]
I think I side with

> Or we just deal with it and say that your @ryancrosby changes provide a better experience regardless.

**Comment by ashfurrow** [comment]
Cool. I like this. If I'm not mistaken, @ryancrosby 's changes would be useful in a test environment where there tests are run multiple times against different iOS simulators? Our experience has been more with running once and mocking the device multiple times, since the views don't exist in the simulator anyway. 

Should this repo provide support for both approaches or have an opinion and go with only one approach? Should this be another library altogether? Open to suggestions on both.

**Comment by orta** [comment]
You'll always be in a simulator of a device though. In either case, maybe the solution is

```
expect(vc).to( haveValidDeviceSnapshot() )
```

Which can skip them if that device doesn't have the snapshot for the device you're testing with

**Comment by ashfurrow** [comment]
Ah, that would work for either strategy. Maybe allow optionally passing in a parameter that defines the device, and if none is provided, it asks UIDevice instead.

**Comment by orta** [comment]
works for me

**Comment by ryancrosby** [comment]
I have been off the swift project I was working on for awhile, so I haven't been able to stay completely up to speed. @ashfurrow by using ```expect(vc)``` do you mean for vc to be a view controller? Or a view?

Meaning a view controller makes alot of sense, sense most of the time a device dependent screen shot will be the root view of a view controller. However I can imagine other times a device dependent expectation would apply, such as table view cells. So passing a view would allow for those other use cases.

I don't think I would recommend using my solution entirely, if I remember correctly SDiPhoneVersion needed some tweaking from me for it to work as desired.

**Comment by orta** [comment]
The pod supports sending a view controller into the expectation, it does some extra work then takes the root view. I don't think we should do different behaviour depending on that here.

**Comment by ryancrosby** [comment]
That makes sense and haveValidDeviceSnapshot can be used separately. I should drink more coffee before jumping in.

**Comment by kevboh** [comment]
Also find myself needing this. @ryancrosby did you ever drink coffee/jump in?

**Comment by ryancrosby** [comment]
No, I didn't. From the looks of things at work, I won't be back on the Swift project for awhile. Here is the code I am currently using https://gist.github.com/ryancrosby/38b3d7ae0192bc72d77b. Because I did this in December and I kept fighting cocoapods and/or frameworks, I ended up just copying in the Nimble source to my project and added this function to the Nimble source. Wish I had more time to help, but hopefully that can get you a working solution.

**Comment by kevboh** [comment]
No, this is super helpful. Thanks.

**Comment by mps** [comment]
did anyone find an approach for this if you use size classes?  right now all screenshots just become 1200x1200 (or 2x the default size class)

**Comment by orta** [comment]
In [eigen](https://github.com/artsy/eigen/) I added [this mock](https://github.com/artsy/eigen/blob/master/Artsy%20Tests/ARTestContext.m#L45) (for iOS8) to allow for setting device sizes in tests that [look like this](https://github.com/artsy/eigen/blob/master/Artsy%20Tests/ARExpectaExtensions.m#L3). I wouldn't be surprised if something like this is one answer.

**Comment by esttorhe** [comment]
@ryancrosby, @kevboh and @mps would you mind checking version `1.2.0`?
I released something called `deviceAgnostic` 

`recordDeviceAgnosticSnapshot` and `haveValidDeviceAgnosticSnapshot` that perhaps address what you guys need.

**Comment by ashfurrow** [comment]
This should be fixed by @esttorhe's work. If not, please feel free to re-open!
