### ISSUE TITLE
"Could not install 'iOSSnapshotTestCase' pod. There is no target that supports it."

### ISSUE THREAD

**Issue by ejmartin504** [ashfurrow/Nimble-Snapshots#153]
I think this may be related to https://github.com/ashfurrow/Nimble-Snapshots/pull/147

When I look at the uber repo, I don't see a version 2.2.0 https://github.com/facebookarchive/ios-snapshot-test-case/blob/master/FBSnapshotTestCase.podspec  -- could that be the root of the problem?

**Comment by ejmartin504** [comment]
Hm, this doesn't seem to be related. Tried installing 6.3.0 and got same error. I think my project set-up is messed up somehow.

**Comment by jgongo** [comment]
@ejmartin504 did you manage to solve this? I'm getting the same error and I can't find the reason

**Comment by ejmartin504** [comment]
TBH @jgongo this was a long time ago and I have no idea how I managed to work around it. Good luck!

**Comment by jgongo** [comment]
Just for the record, I solved this explicitly adding the `iOSSnapshotTestCase` dependency to the podspec. Why? I really don't know:

```ruby
  s.test_spec 'Tests' do |t|
    t.source_files = ...

    t.dependency 'Quick', '~> 1.2'
    t.dependency 'Nimble', '~> 7.0'
    t.dependency 'Nimble-Snapshots', '~> 6.9'
    t.dependency 'iOSSnapshotTestCase', '~> 4.0' # Not adding this causes pod install to fail
  end
```
