### ISSUE TITLE
Snapshot tests fail to run

### ISSUE THREAD

**Issue by danielsaidi** [ashfurrow/Nimble-Snapshots#155]
Hi!

I have used Nimble Snapshots for a long time, but not upgraded since FBSnapshotTestCase became an Über library. When I now install it together with Nimble Snapshots, using Carthage, the test suite fails to run altogether, e.g.:

```
it("has valid snapshots for all colors") {
   let colorView = view(forColor: .blue)
   expect(colorView).to(haveValidSnapshot())
}
```

No matter if I run this or `recordSnapshot()`, the test suite just fails without even executing the tests. If I place a breakpoint at the colorView line, the breakpoint is not triggered.

If I remove `haveValidSnapshot()` from the code above, the test suite runs perfectly and the breakpoint is triggered.

Any ideas?

**Comment by danielsaidi** [comment]
Cleaning derived data and the build folder and restarting Xcode did not help, but doing all that AND restarting the computer gave me a crash log to go on, and helped me solve the problem.

**Comment by ashfurrow** [comment]
@danielsaidi I'm glad you got it figured out! I'm curious what the problem was, if you're able to share?

**Comment by ashfurrow** [comment]
Gotcha, thanks. That happens!
