### ISSUE TITLE
set Reference Image folder

### ISSUE THREAD

**Issue by maryamaffinityclick** [ashfurrow/Nimble-Snapshots#158]
Im having trouble setting the reference images folder. 
is that what I suppose to do ? 

        `FBSnapshotTest.setReferenceImagesDirectory(ProcessInfo.processInfo.environment["IMAGE_REF_DIR"])`

Just setting the `IMAGE_REF_DIR` as environment variable didn't work. so I use this method to pass it. but still says ` expected a matching snapshot in ChooseProfileName_XS`  . 
even I tried to record first in this path but says `expected to record a snapshot in ChooseProfileName_XS `

Where am I doing wrong ? any idea ?

P.S. the path Im trying is in user/documents  ... which is not the path in project folder.

**Comment by ashfurrow** [comment]
Hmm! I'm not sure, I've never set the reference image directory manually before. If you toss out the env var and just call `FBSnapshotTest.setReferenceImagesDirectory()` with a hardcoded value? Anyone else see this before?

**Comment by maryamaffinityclick** [comment]
Im sorry that was not the issue, I had problem of not having different snapshots for different device sizes.  
That code above is correct and is actually what we have to do in order to change the reference image directory.
