### ISSUE TITLE
Nimble Carthage

### ISSUE THREAD

**Issue by balichowdry** [ashfurrow/Nimble-Snapshots#166]
Hi 

I am using Xcode10
Carthage 0.29.0
Swift version 4.2
Nimble "v7.0.3"

when I update Carthage I get this error, can you please help me I am not sure is Carthage issue with latest Xcode or Nimble issue

Carthage/Checkouts/Nimble/Sources/NimbleObjectiveC/NMBExceptionCapture.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by Vkt0r** [comment]
@balichowdry Please feel free to open this if continues happening 😃.
