### ISSUE TITLE
Failed snapshots are not saved in IMAGE_DIFF_DIR but in NSTemporaryDirectory()

### ISSUE THREAD

**Issue by mihai8804858** [ashfurrow/Nimble-Snapshots#169]
After updating https://github.com/uber/ios-snapshot-test-case and https://github.com/ashfurrow/Nimble-Snapshots to latest versions (`4.0.0` and `6.8.1`), failed snapshots started to not being recorded in specified `IMAGE_DIFF_DIR` from scheme but in `NSTemporaryDirectory()`.
Looking into #162 it seems that directory is hardcoded to `NSTemporaryDirectory()` and `IMAGE_DIFF_DIR` is ignored.

**Comment by ashfurrow** [comment]
Good morning! Looks like you've found a bug – would you be able to open a pull request that fixes it?

**Comment by flobories** [comment]
Hello 👋I just encountered this same issue in my project.
I published a simple PR #171 that checks if the environment variable `IMAGE_DIFF_DIR` is set and defaults to the temporary folder if not. I confirmed it worked on my machine.
Let me know what you think!
