### ISSUE TITLE
CI Failure

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Nimble-Snapshots#170]
[Seen here](https://circleci.com/gh/ashfurrow/Nimble-Snapshots/144) after merging [#163](https://github.com/ashfurrow/Nimble-Snapshots/pull/163). I'll take a look when I can unless someone beats me to it.

**Comment by freak4pc** [comment]
Very interesting. I’ll be able to get to this on Saturday but imagine someone else will get there first :)

**Comment by Vkt0r** [comment]
Uhmm yep, I know what's happening with second_curtain. Fixing that now :).

**Comment by Vkt0r** [comment]
@ashfurrow #172 fixes the issue with `second_curtain` but I think we have some kind of cache issue with CircleCI, as far as I can see we have 2 PR derived from `master` and both are green 🤯. What do you think ?

**Comment by ashfurrow** [comment]
Dunno! The new caching stuff with Circle CI 2.0 is pretty weird, wouldn't be surprised if we ran into something weird. I've merged #172, let's see what happens! 🙃

**Comment by ashfurrow** [comment]
Weird, got a _different_ failure: https://circleci.com/gh/ashfurrow/Nimble-Snapshots/156

**Comment by ashfurrow** [comment]
Hmm! That's very strange. Ugh, yeah I didn't see it either. If it's intermittent, let's rerun the build. We should open a new issue to fix the second_curtain run, though to be honest, it might be better just to use the capability added in #171 to put the image diffs in a directory, then upload the directory as a Circle CI artifact? https://circleci.com/docs/2.0/artifacts/#uploading-artifacts

**Comment by Vkt0r** [comment]
Yes, we could that very easy saving the artifacts.

**Comment by Vkt0r** [comment]
@ashfurrow You're very welcome 😀, but thanks to you for all your dedication to open source projects like this 🙌. You're an inspiration in the community for all your hard work to share more every day! Thanks for it.

**Comment by Lascorbe** [comment]
This was fixed, right? I'm closing it then. Feel free to reopen/open a new one if it's not the case. Thanks all!
