### ISSUE TITLE
Swift 4.2 Compatiablity

### ISSUE THREAD

**Issue by DJingSeo** [ashfurrow/Nimble-Snapshots#174]
As NSLayoutAttribute has changed to NSLayoutConstraint.Attribute and childViewControllers property of UIViewContoller has changed to children, the current Nimple-Snapshots can't be built based on Swift 4.2.

**Comment by DJingSeo** [comment]
After I forked, I found that you have already fixed. Sorry for the confuse.

**Comment by ashfurrow** [comment]
No worries!

**Comment by ashfurrow** [comment]
I just pushed this as 6.9.0 so you should be able to install it now from CocoaPods trunk.
