### ISSUE TITLE
Xcode 10.2 / swift 5 Compatability

### ISSUE THREAD

**Issue by cohen72** [ashfurrow/Nimble-Snapshots#185]
pretty please :)

**Comment by ashfurrow** [comment]
Hey, yeah! Definitely something I'm interested in. Artsy is using this with Xcode 10.2 already, though we're still on Swift 4.x. If you have time, it would be awesome to get a pull request with the updates :bow: Otherwise, I (or one of the other contributors) will get to it when we can.
