### ISSUE TITLE
[Proposal] Expose the `switchChecksWithRecords` as public.

### ISSUE THREAD

**Issue by ignazioc** [ashfurrow/Nimble-Snapshots#186]
I like this framework, but I find a bit tedious to:

> replace haveValidSnapshot() with recordSnapshot()

every time I want to re-record all the tests for a specific view.

Reading the source code I found the `switchChecksWithRecords` variable  ([link](https://github.com/ashfurrow/Nimble-Snapshots/blob/8ac7611079a9d31af50390d209bd9a61f80b6e72/Nimble_Snapshots/HaveValidSnapshot.swift#L258)) that can be used to solve this problem.

My proposal is to rename this variable to `recordSnapshot` and expose it as public.

Using that value the users can leave all the `haveValidSnapshot` on the code, and just editing one variable re-record all the test.

If you like the idea I'll create a PR.

**Comment by ashfurrow** [comment]
Hey, what a good idea! To be honest, I usually go in and change this manually in the code anyway when I want to re-record anything. A PR to rename and expose it publicly sounds great – thank you! We should include a note in the readme about how to do that, ideally with a `beforeSuite` Quick example block.

**Comment by dogo** [comment]
@ignazioc , please update to 8.20
