### ISSUE TITLE
Move to CocoaPods trunk

### ISSUE THREAD

**Issue by orta** [ashfurrow/Nimble-Snapshots#19]

**Comment by ashfurrow** [comment]
Hmm. Looks like Quick isn't on trunk yet. Let's see if we can get that sorted first.

**Comment by ashfurrow** [comment]
OK, once [these](https://github.com/Quick/Nimble/pull/81) [two](https://github.com/Quick/Quick/pull/239) PRs are merged and Quick and Nimble are up on Trunk, I'll push Nimble-Snapshots.

**Comment by ashfurrow** [comment]
Nimble and Quick are now on Trunk, but there is still another problem: https://github.com/facebook/ios-snapshot-test-case/issues/58
