### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by leo1mml** [ashfurrow/Nimble-Snapshots#190]
Any chance on making this framework compatible with SPM? If it is already possible, could you guys add a description on Readme.md about how to do it?

**Comment by Vkt0r** [comment]
@leo1mml Thanks for the suggestion! Unfortunately we're two dependencies in our library:

 - [Quick](https://github.com/Quick/Quick)
 - [ios-snapshot-test-case](https://github.com/uber/ios-snapshot-test-case)

Quick supports SPM, but ios-snapshot-test-case not. They opened this [issue](https://github.com/uber/ios-snapshot-test-case/issues/91) related to that. Until this is handled it we can't add support for SPM here. But let's keep this open to keep track of it.

**Comment by bfernandesbfs** [comment]
Open MR - Support SPM into `ios-snapshot-test-case` 

* https://github.com/uber/ios-snapshot-test-case/pull/107

**Comment by Vkt0r** [comment]
Awesome @bfernandesbfs I saw your PR yesterday, please let us know as soon as is merged it in order to add support here!

**Comment by noppefoxwolf** [comment]
https://github.com/noppefoxwolf/Nimble-Snapshots/tree/spm

I implemented Package.swift for my self.

**Comment by ashfurrow** [comment]
Cool! Good work, @noppefoxwolf. Would you be interested in opening a pull request to get this supported in this repo?

**Comment by bfernandesbfs** [comment]
It's working 😍
