### ISSUE TITLE
Xcode 11.4 Compilation Error - Missing XCTestSwiftSupport

### ISSUE THREAD

**Issue by joeydong** [ashfurrow/Nimble-Snapshots#196]
Hey, I'm getting a compilation error while trying to execute `carthage bootstrap` with Xcode 11.4. 

I'm able to reproduce the issue by building this project with Xcode 11.4 on master 061207b06f5b2ef40dcf075ceb2e841bd2657cc3:

<img width="1890" alt="Screen Shot 2020-03-30 at 2 39 20 PM" src="https://user-images.githubusercontent.com/434294/77964697-567d4d00-7294-11ea-9f1c-ef4266756ada.png">

Looks like the build error is related to this comment in the Xcode 11.4 Release Notes:

> Xcode introduced an “Enable Testing Search Paths” build setting to improve support for test support frameworks and libraries. This build setting is on by default for test bundle targets, as well as for targets which explicitly include XCTest.framework in their “Link Binary With Libraries” list. Source files in such targets can now import XCTest without setting any custom search paths. (51117167)

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes

So setting `ENABLE_TESTING_SEARCH_PATHS = YES` or linking "XCTest.framework" fixes the error, but I have no idea what the release note means 😅 

Any ideas for next steps?

**Comment by ashfurrow** [comment]
Hey, thanks for the detailed issue! The Carthage build settings are determined with the `Nimble_Snapshots.xcodeproj` Xcode project in the root of this repository. Setting the `ENABLE_TESTING_SEARCH_PATHS` value in that Xcode project's build settings _should_ be enough to fix the error. 

Would you have time for a PR? I haven't downloaded the latest beta yet 🙈

**Comment by joeydong** [comment]
Yup! https://github.com/ashfurrow/Nimble-Snapshots/pull/197

**Comment by ashfurrow** [comment]
Okay, I've created a GitHub release with #197 merged: [8.1.2](https://github.com/ashfurrow/Nimble-Snapshots/releases/tag/8.1.2). My understanding is that you should be able to update the library with Carthage and see the change. Let me know how it goes 👍
