### ISSUE TITLE
Support Nimble 9.0

### ISSUE THREAD

**Issue by joridor** [ashfurrow/Nimble-Snapshots#202]
Due to an issue with our tests with Nimble 8.4 on Xcode 12, we had to update to Nimble v9 RC.
Is it possible to update Nimble-Snapshots to a version that has Nimble v9 as a dependency (when it is officially released)?

**Comment by ashfurrow** [comment]
Yes definitely we can do that. I'm happy to release a new version of Nimble-Snapshots once Nimble 9 is out. I think the easiest path forward is to change this line:

https://github.com/ashfurrow/Nimble-Snapshots/blob/4a7fe49a48f67e060a08d2df67880221f7219dad/Nimble-Snapshots.podspec#L25

from `ss.dependency "Nimble", "~> 8.0"` to `ss.dependency "Nimble"`. This removes the version requirement altogether, at the risk of introducing breaking changes down the road when (for example) Nimble 10 is released. Does that sound okay to you? Would you like to submit a PR?
