### ISSUE TITLE
Add support for swift package manager

### ISSUE THREAD

**Issue by tahirmt** [ashfurrow/Nimble-Snapshots#215]
Can we get SPM support?

**Comment by ashfurrow** [comment]
Sure can! I think that's a great idea. [You can open a pull request here](https://github.com/ashfurrow/Nimble-Snapshots/compare?expand=1).

**Comment by tahirmt** [comment]
This will be a good addition. Still trying to figure out how to get Swift and Objective-C work together while using SPM

**Comment by hfehrmann** [comment]
The problem is that there is a dependency that will not be updated to work with SPM. See #190

**Comment by tahirmt** [comment]
@ashfurrow I worked on this on a fork by using this fork https://github.com/alanzeino/ios-snapshot-test-case.git. The main repo is still now updated because uber isn't maintaining the repo. Not sure if we want to add support by using a fork instead of the main repo though so I didn't create a pull request here.

**Comment by ashfurrow** [comment]
Hmm, I can only speak from a CocoaPods perspective, where it's fairly easy to use a fork (by adding the transitive dependency to your `Podfile` using `git` to point to the fork). It's a shame Uber isn't maintaining that – I'm glad Alan is on it though.

**Comment by tahirmt** [comment]
Pointing to a fork with swift package manager is even easier imo. For my fork I only used the fork for the swift package https://github.com/tahirmt/Nimble-Snapshots/pull/1. 

Alan has been trying to get access to the repo and "we should know in a few weeks"
https://github.com/uber/ios-snapshot-test-case/pull/126#issuecomment-857981269

**Comment by dogo** [comment]
It's possible now! I'm on it
