### ISSUE TITLE
Global flag for recording instead of testing

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Nimble-Snapshots#22]
It would be cool to have, as a part of the matcher, a global flag you could set once to re-record all snapshot images. /cc @orta

**Comment by ashfurrow** [comment]
We have this now: https://github.com/ashfurrow/Nimble-Snapshots/blob/8199e5b4a8cef59303097da894c3c1d728d9e853/HaveValidSnapshot.swift#L158

You have to modify it in-place, which I like. Closing.

**Comment by esttorhe** [comment]
Would it be possible to maybe read the value from a key on the `Info.plist` perhaps?

The reason I'm asking is because I created the `deviceAgnostic` logic to test on multiple devices and `OS`s; using `Xcode Bots` I can easily test against a variety of devices but the only way I can actually record this would be to fork the repo with this flag set to `true` always for recording and then switch to the official pod for testings (?)

Because it pulls the `pods` as a «pre» script.

Was wondering if maybe reading it from a more «customizable» place would be possible

**Comment by ashfurrow** [comment]
Hmm, hadn't considered generating snapshots as a part of regular CI _outside_ the context of comparing them. 

This flag is really if you change something fundamental, like the iOS version, and want to re-run the tests to replace _every_ image. 

If it makes sense to include this outside of modifying the source code, then let's re-open the issue.

**Comment by esttorhe** [comment]
Well; is not a normal scenario to use `CI` to record the snapshots; but for multiple devices and `OS`s its easier to do it like this than to manually iterate over all the options; hence why I was thinking in adding it to a more customizable location

**Comment by ashfurrow** [comment]
Hmm, but that's the use case I'm describing. I don't feel like having an option to do this in code is really necessary. It's not a change you'd want to check in – whether you add a call to this library to change the variable, or change the library's code itself, it doesn't really make a difference in my opinion. Having it not included as a call (but maybe documented in the readme) to me sounds like the best approach, but I'm open to suggestions.

**Comment by ashfurrow** [comment]
Gonna re-open for now until we come to a conclusion.

**Comment by orta** [comment]
I'm on the side of not needing exposed code for this, I've had to do this in the past, and I just [scripted it](https://github.com/artsy/Artsy-UIColors/blob/master/Rakefile#L92)

``` ruby
desc "Updates the test snapshots"
task :new_snapshots do
    before = "snapshotController.recordMode = record"
    after = "snapshotController.recordMode = YES"
    
    path = "Pods/Expecta+Snapshots/EXPMatchers+FBSnapshotTest.m"
    new_file = File.open(path).read.gsub(before, after)
    File.open(path, 'w') { |tmp| tmp.write(new_file) }
    
    `rm -rf UnitTests/ReferenceImages/`
    `xcodebuild -workspace UnitTests.xcworkspace -scheme UnitTests -sdk iphonesimulator -destination 'name=iPhone 6' build test`
    
    new_file = File.open(path).read.gsub(after, before)
    File.open(path, 'w') { |tmp| tmp.write(new_file) }
end
```
