### ISSUE TITLE
Migrate to new CI provider

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Nimble-Snapshots#220]
Circle CI has started requiring us to pay for macOS build infrastructure, probably a consequence of increasing friction from Apple's macOS EULA and cryptocurrency miners abusing free cloud infrastructure. What a shame.

Anyway, we should migrate to a new CI provider. GitHub Actions is getting lots of attention lately, and it's free, so let's explore that.

**Comment by dogo** [comment]
@ashfurrow I made the initial migration, but we can improve a lot. Please, feel free to let me know if you require any further information.
