### ISSUE TITLE
compiler error on building with Nimble-Snapshots 9.1.0 using Carthage on Xcode 12.5, Swift 5.4

### ISSUE THREAD

**Issue by harshithagit33** [ashfurrow/Nimble-Snapshots#224]
compiler error on building with Nimble-Snapshots 9.1.0 using Carthage on Xcode 12.5, Swift 5.4

/Carthage/Checkouts/Nimble-Snapshots/Nimble_Snapshots/PrettySyntax.swift:1:8:   error: module compiled with Swift 5.2.4 cannot be imported by the Swift 5.4   compiler:
--
Carthage/Checkouts/Nimble-Snapshots/Carthage/Build/iOS/Nimble.framework/Modules/Nimble.swiftmodule/arm64-apple-ios.swiftmodule     import Nimble     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^          ** ARCHIVE FAILED **               The following build commands failed:     	CompileSwift normal armv7     	CompileSwiftSources normal armv7   com.apple.xcode.tools.swift.compiler     	CompileSwift normal arm64     	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler     (4 failures)
--

**Comment by ashfurrow** [comment]
We're going to need more details about the failure in order to diagnose the problem here.

**Comment by harshithagit33** [comment]
I am trying to update my project using carthage with following version. and i face the error mention while running 

carthage update --platform iOS

XCode 12.5, Swift 5.4

github "Quick/Nimble" == 9.2.0
github "Quick/Quick" == 4.0.0
github "ashfurrow/Nimble-Snapshots" == 9.1.0

**Comment by ashfurrow** [comment]
Okay thanks. I'm not a Carthage user, but hopefully someone will be able to help you out. Let us know if you have like a stack trace or any further details. PRs are welcome too.

**Comment by dogo** [comment]
@woutergoossens Please update to 9.4.0
