### ISSUE TITLE
Compiler Errors After Installation

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Nimble-Snapshots#23]
We depend on `FBSnapshotTestCase` with a version specifier of `~> 1.5`, but `FBSnapshotTestCase` 1.6 introduced breaking changes, so we need to update our use of it.

**Comment by orta** [comment]
ah yeah, totally, I only updated Expecta+Snapshots

**Comment by ashfurrow** [comment]
¯\\_(ツ)_/¯

**Comment by ashfurrow** [comment]
Fixed in 0.4.0.
