### ISSUE TITLE
Can't import FBSnapshotTestCase in HaveValidSnapshot.swift after update to iOSSanpshotTestCase 8.0.0

### ISSUE THREAD

**Issue by brandtdaniels** [ashfurrow/Nimble-Snapshots#240]
Can't import FBSnapshotTestCase in HaveValidSnapshot.swift when resolving swift package on master due to the update in the dependency:

        .package(name: "iOSSnapshotTestCase",
                 url: "https://github.com/uber/ios-snapshot-test-case.git",
                 .upToNextMajor(from: "8.0.0")),

**Comment by diogot** [comment]
It's working now, thanks!
