### ISSUE TITLE
Swift Package Manager - class name is not removed from snapshot image name 

### ISSUE THREAD

**Issue by woutergoossens** [ashfurrow/Nimble-Snapshots#246]
We are updating our Carthage Implementation  to SPM. 
With that change, our snapshots are invalid because the class name is not removed in the sanitizedName var in CurrentTestCaseTracker.

` if let quickClass = NSClassFromString("QuickSpec"), self.isKind(of: quickClass) {`
--> will fail because QuickSpec does not exists. By using NSClassFromString in Swift, the module/app name should also be used so it should be NSClassFromString("Quick.QuickSpec").

```
BEFORE AccountDetailsLoadingView__should_show_a_standard_loadingView
AFTER MySpec_AccountDetailsLoadingView__should_show_a_standard_loadingView
```

Can that be updated in case of Swift Package Manager?

test project --> [NimbleTest.zip](https://github.com/ashfurrow/Nimble-Snapshots/files/8584168/NimbleTest.zip)

**Comment by dogo** [comment]
Hi @woutergoossens , working on it

**Comment by dogo** [comment]
@woutergoossens Please update to 9.4.0

**Comment by woutergoossens** [comment]
> @woutergoossens Please update to 9.4.0

Thanks!
