### ISSUE TITLE
Empty Snapshot Names

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Nimble-Snapshots#25]
Happening in Eidolon.

**Comment by ashfurrow** [comment]
Still seeing this: 

![screen shot 2015-11-04 at 2 48 25 pm](https://cloud.githubusercontent.com/assets/498212/10949863/213ff082-8303-11e5-899d-ba63daf1b7f1.png)

**Comment by kevboh** [comment]
Also seeing this, FWIW. I actually didn't know there were supposed to be names there until I saw this issue—we've only ever gotten that error message on mismatch.

**Comment by orta** [comment]
I was seeing this, I think #45  fixes this here https://github.com/ashfurrow/Nimble-Snapshots/pull/45/files#diff-7fce22a4b2b1f0d0561c7e2f46314a46R136

**Comment by orta** [comment]
Was this a quick problem?

**Comment by ashfurrow** [comment]
Seems likely, they did [a lot of work](https://github.com/Quick/Quick/pull/295) on how tests names are printed to the console for the 0.9.1 release. I think it's likely that that work inadvertently fixed our problem.

**Comment by marcelofabri** [comment]
@ashfurrow Can we close this?

**Comment by orta** [comment]
👍
