### ISSUE TITLE
Release with Nimble v11 support

### ISSUE THREAD

**Issue by diogot** [ashfurrow/Nimble-Snapshots#254]
Hi,

I saw that you merged a PR with support to Nimble v11, nice work!
When are you planning to have a new release with it? (I'm interested in SPM)
Is this a think that I can help with?

Thanks!

**Comment by ashfurrow** [comment]
This should already be available in version 9.5.0 👍

**Comment by diogot** [comment]
It was available indeed, but there was a misconfiguration in the `Package.swift`, I fixed and opened a PR (#255).

**Comment by diogot** [comment]
Fixed in version 9.5.1.
