### ISSUE TITLE
Is there a possibility to record the failed snapshot automatically?

### ISSUE THREAD

**Issue by AhmedAskar** [ashfurrow/Nimble-Snapshots#267]
I was thinking of the possibility to check if there is something that can automatically record the failing snapshot tests instead of replacing the code with `recordSnapshot` and `haveValidSnapshot`?

**Comment by contreras2004** [comment]
Doesn't this defeat the purpose of checking if the snapshots are equal? The developer should know that the tests are failing and manually record the new snapshots. Maybe you are looking for a way of recording all snapshots again?

If so you could use the following function defined in **FBSnapshotTest**

```
public func recordAllSnapshots() {
    switchChecksWithRecords = true
}
```

**Comment by ashfurrow** [comment]
Sometimes it's necessary to re-generate all images, like when you're updating the iOS version on CI. I would use [`recordAllSnapshots`](https://github.com/ashfurrow/Nimble-Snapshots/blob/9e4ab0a00b3d0f1d6d2d358e5886532f87503d10/Nimble_Snapshots/HaveValidSnapshot.swift#LL128C13-L128C31) as @contreras2004 suggested 👍
