### ISSUE TITLE
Pull Request 268 Released?

### ISSUE THREAD

**Issue by Ripcord715** [ashfurrow/Nimble-Snapshots#269]
Hi there!

Apologies if this isn't the right place to ask this, or if I'm just missing something obvious somewhere, but has [PR 268](https://github.com/ashfurrow/Nimble-Snapshots/pull/268) been released in an update? I'm running into the issue that fix corrects, and after setting my SPM to v9.5.1 (I saw that's the Cocoapods latest version) I'm not seeing what was included in that fix, so I just wanted to check to make sure. If it hasn't been released yet, is there any idea when?

Thank you very much for your help!

**Comment by treastrain** [comment]
I am waiting for this release too! Thank you.

**Comment by treastrain** [comment]
I'm waiting for this release too! Thank you.

**Comment by Macjon** [comment]
Hi @ashfurrow is it possible to create a new spm package please? We all need it 😉

**Comment by ashfurrow** [comment]
I will get this released this week.

**Comment by ashfurrow** [comment]
#268 has been released as a [GitHub tag/release](https://github.com/ashfurrow/Nimble-Snapshots/releases/tag/9.6.0), which should support SPM and Carthage. It's also been released to CocoaPods with the same version. Let me know if there are any issues.
