### ISSUE TITLE
Can we have a new version for SPM which is compatible with nimble 12?

### ISSUE THREAD

**Issue by drademacher** [ashfurrow/Nimble-Snapshots#273]
I currently have to use the master for of Nimble-Snapshots, because the newest release is not compatible with nimble 12. Can we have a version bump for SPM?

**Comment by ashfurrow** [comment]
#268 with support for Nimble 12 / Xcode 15 has been released as a [GitHub tag/release](https://github.com/ashfurrow/Nimble-Snapshots/releases/tag/9.6.0), which should support SPM and Carthage. It's also been released to CocoaPods with the same version. Let me know if there are any issues.
