### ISSUE TITLE
Xcode 15/Swift 5.9 Problems

### ISSUE THREAD

**Issue by gholias** [ashfurrow/Nimble-Snapshots#274]
I've just updated to xcode 15 and our test target does not build anymore.

<img width="407" alt="Screenshot 2023-09-27 at 9 00 10 AM" src="https://github.com/ashfurrow/Nimble-Snapshots/assets/75060/7a03b280-6252-4dde-8634-da8e39260dda">

Is there a known workaround?

**Comment by agripinogabriel** [comment]
Waiting the release of https://github.com/ashfurrow/Nimble-Snapshots/pull/268

**Comment by ashfurrow** [comment]
I will try to release this this week.

**Comment by ashfurrow** [comment]
#268 has been released as a [GitHub tag/release](https://github.com/ashfurrow/Nimble-Snapshots/releases/tag/9.6.0), which should support SPM and Carthage. It's also been released to CocoaPods with the same version. Let me know if there are any issues.
