### ISSUE TITLE
Issue with Xcode 16 beta 3

### ISSUE THREAD

**Issue by Ripcord715** [ashfurrow/Nimble-Snapshots#281]
While testing my company's project with Xcode 16 beta 3 to try to get ahead of any potential issues, I found that Nimble-Snapshots was breaking in places when I tried to run our test automation. It wanted me to change Expression<T> to Nimble.Expression<T> in order to get rid of those errors.

The places I saw these errors were:
DynamicSizeSnapshot - line: 177
HaveValidDynamicTypeSnapshot - line: 106
HaveValidSnapshot - lines: 209 & 237

I forked the Nimble-Snapshots project and made these changes, but when I tried to point my company's project to my forked version on Nimble-Snapshots, Xcode kept crashing (_I fully realize this could be due to my inexperience as a dev, and Swift Package Manager - lol_). Since I'm unable to test this with my project, and am unable to test my forked Nimble-Snapshots version with a previous Xcode version, I just wanted to put it on y'alls radar for the future.

**Comment by Ripcord715** [comment]
Hi just touching base to see if anyone has had a chance to look at this.

**Comment by ashfurrow** [comment]
Thanks for opening an issue about the problem. I don’t use Nimble-Snapshot day to day anymore, but there are lots of maintainers here who do. 

To help figure out the problem, could you add details about the specific compilers errors? Can you point to the changes you made on your fork that fixed them, and provide any details about the Xcode crash?

While I likely won’t be the one to fix these myself, I’m happy to bounce ideas around and help us figure it out together.

**Comment by ashfurrow** [comment]
Oh I just saw your PR #282 that is super helpful. I’ll take a look, but I’ll be busy until tomorrow night at the earliest. Thanks again!

**Comment by Ripcord715** [comment]
No worries, thank you very much!

**Comment by Ripcord715** [comment]
Hi Ash! Just dropping a friendly reminder! I'm sure you're busy, so no worries!

**Comment by ashfurrow** [comment]
Ripcord's PR was just released as `9.8.0`.
