### ISSUE TITLE
Release new pod 🙏

### ISSUE THREAD

**Issue by esttorhe** [ashfurrow/Nimble-Snapshots#34]
@ashfurrow or @orta don't know if any of you guys could release a new version of this that contains my device agnostic code; right now i'm pointing at the `git` with `branch: "master"` which is not optimal (IMHO)

:pray:

**Comment by ashfurrow** [comment]
Ah, whoops. Yeah hold on.

**Comment by esttorhe** [comment]
Yeah no problem; would have done it myself if i could :stuck_out_tongue:

**Comment by ashfurrow** [comment]
What's your email address?

**Comment by esttorhe** [comment]
`me@estebantorr.es`

**Comment by ashfurrow** [comment]
Cool, added you as an owner of the pod. Trying to push to trunk but I'm getting errors. Looking into it now.

**Comment by esttorhe** [comment]
:ok_hand: sweet :tada: 

If you can't for whatever reason I can pull from git and push to trunk if needed

**Comment by ashfurrow** [comment]
The problem is with this: https://github.com/facebook/ios-snapshot-test-case/issues/128 We rely on a class that was made internal for some reason. Facebook are changing it back but until they release a new version, we're stuck :grimacing:

**Comment by esttorhe** [comment]
Ah yeah… the custom made `.modulemap` issue.

Had to lock that to `2.0.5` on my `podfile`.

That's ok; I'll release a new `pod` when they revert it :wink: 


Thanks a lot :bow:

**Comment by ashfurrow** [comment]
:tada:

**Comment by esttorhe** [comment]
Ok; new version is out with `FBSnapshotTestCase` `2.0.7` dependency and «device agnostic» support.

Also `1.2.0` pod is out as well

**Comment by ashfurrow** [comment]
:tada:
