### ISSUE TITLE
📷 emoji function doesn't detect correct folder for snapshots

### ISSUE THREAD

**Issue by neilkimmett** [ashfurrow/Nimble-Snapshots#40]
The 📷 doesn't seem to pass through the correct file to search for the snapshot folder in. Not a huge problem cause I can just use `expect(vc).to(recordSnapshot())` instead. Might try to fix if I take some time off reading about Swift OSS 🤗

Using `expect(vc).to(recordSnapshot())`
<img width="778" alt="nimble snapshots right" src="https://cloud.githubusercontent.com/assets/1180883/11589191/61122f9e-9a7e-11e5-9c1c-46df1082e94a.png">

Using `📷(vc)`
<img width="829" alt="nimble snapshots wrong" src="https://cloud.githubusercontent.com/assets/1180883/11589194/6befc656-9a7e-11e5-9d24-6587c4e8b6bb.png">

**Comment by ashfurrow** [comment]
Whoa, great catch! Hmm.. not super-easy to fix. I'll give a think. Thanks for letting me know!

**Comment by neilkimmett** [comment]
My pleasure. Have yourself a fabulous Friday 
![thumbsup](https://cloud.githubusercontent.com/assets/1180883/11591500/25131bae-9a90-11e5-99c6-08a687cc891e.gif)

**Comment by madnik** [comment]
+1

**Comment by orta** [comment]
Interesting, looks like the problem @alloy was having too

**Comment by orta** [comment]
can the emoji work with default args on function passing in line / file number?

**Comment by ashfurrow** [comment]
Hmm, I'm not sure. It would explain things, maybe time to remove the emoji operator?

**Comment by orta** [comment]
Fixed in #45
