### ISSUE TITLE
view hierarchy is captured without 3D transform

### ISSUE THREAD

**Issue by paulz** [ashfurrow/Nimble-Snapshots#42]
We have views that use `CALayer.transform` of `CATransform3D` type and they are captured by snapshot as if no transform has been set.

**Comment by ashfurrow** [comment]
Hmm! Interesting. Any suggestions on how to fix? Likely something to do with Facebook's snapshot library. 
-- 
Ash Furrow
https://ashfurrow.com/

**Comment by orta** [comment]
Yeah, this issues should go on https://github.com/facebook/ios-snapshot-test-case
