### ISSUE TITLE
Xcode 7.3 Support?

### ISSUE THREAD

**Issue by tbondwilkinson** [ashfurrow/Nimble-Snapshots#49]
I can't get this to work with Xcode 7.3.  No matter what I do, the tests aren't recognized and aren't run.

Is this a known issue or is this just a problem with the way I've set things up?  I followed the instructions exactly

**Comment by ashfurrow** [comment]
Hey, sorry you're having problems! I need some more information before I can help: what version of the library are you using, of cocoapods, quick, and nimble? Is this on a fresh project or one you've upgraded to Xcode 7.3? The tests aren't being recognized, does that mean Xcode executes other (non-snapshot) tests? Or it doesn't run any tests at all? Can you provide us with a test file the is misbehaving? Double check your test files are in the test target too.

**Comment by tbondwilkinson** [comment]
You're quick on the response thanks!

The latest -- 4.0.  It's a project that's been upgraded to 7.3.  It runs all tests except Nimble/Quick tests, and looking through Quicks open issues it seems Xcode 7.3 has been somewhat of an issue so I was wondering if you had experienced something similar.

If this isn't something other people are experiencing I'll make a one-off project to see if I can't reproduce the error.

**Comment by tbondwilkinson** [comment]
And as an aside, I think it MAY have something to do with the extension of XCTestCase.  The tests that work are extending the Swift XCTestCase, but these tests are actually extending the Objc XCTestCase and I'm wondering if Xcode is getting confused by that...

**Comment by ashfurrow** [comment]
Hmm, I've not heard of this. Yeah, try on a fresh project of you can. Thanks!

**Comment by tbondwilkinson** [comment]
Womp it worked just fine in isolation... great...

Suggestions for debugging would be welcome but otherwise looks like this is just one I have to slog through.

**Comment by ashfurrow** [comment]
😬  yikes. If it's all the quick tests that aren't running, I would open an issue on Quick; someone there might be helpful in tracking it down. They're really nice people.

**Comment by tbondwilkinson** [comment]
That wasn't so bad -- for anyone else who runs into this admittedly very specific bug, it has to do with the fact that I created a new Build Configuration.  Cocoapods got all mixed up and the frameworks were looking in the wrong Build folder in Products (so the frameworks files were not shown).  It'll compile just fine but it won't recognize the frameworks properly.  The fix is to create a new Scheme to go along with that build configuration, this was a great resource (https://christiantietze.de/posts/2015/10/cocoapods-custom-build-configuration/), feel free to reach out to me if you stumble across a similar situation and need more details.  My reason for having a new Build Configuration was to get a preprocessor flag (don't ask).  Thanks @ashfurrow!

**Comment by ashfurrow** [comment]
Glad you got it sorted! Thanks for posting your solution, I'm sure it will come in handy to others :smile:
