### ISSUE TITLE
Extension for turning on/off snapshots for entire classes

### ISSUE THREAD

**Issue by tbondwilkinson** [ashfurrow/Nimble-Snapshots#52]
Hi!

So I've really been loving this for testing but I've been bummed when I had to change `recordSnapshot` to `haveValidSnapshot` and vice versa all across a subset of tests when I deleted the folder or updated wide reaching changes.  So I came up with this extension:

```swift
enum NimbleSnapshotTestAction {
    case HaveValidSnapshot
    case RecordSnapshot

    func performSnapshotAction(
        named name: String?, usesDrawRect: Bool,
              tolerance: CGFloat?) -> MatcherFunc<Snapshotable>
    {
        switch self {
        case .HaveValidSnapshot:
            return haveValidSnapshot(named: name, usesDrawRect: usesDrawRect, tolerance: tolerance)
        case .RecordSnapshot:
            return recordSnapshot(named: name, usesDrawRect: usesDrawRect)

        }
    }
}

protocol NimbleSnapshotTest {
    var snapshotAction: NimbleSnapshotTestAction { get }
}

extension NimbleSnapshotTest where Self: XCTestCase {
    func performSnapshotAction(
        action: NimbleSnapshotTestAction? = nil,
        named name: String? = nil, usesDrawRect: Bool = false,
              tolerance: CGFloat? = nil) -> MatcherFunc<Snapshotable>
    {
        return (action ?? snapshotAction).performSnapshotAction(named: name, usesDrawRect: usesDrawRect, tolerance: tolerance)
    }
}
```

This allows me to to do things like:

```swift
class TestNimbleSnapshotSpec: QuickSpec, NimbleSnapshotTest {
    var snapshotAction: NimbleSnapshotTestAction = .HaveValidSnapshot

    override func spec() {
        let view = UIView()
        let snapshotAction = self.snapshotAction
        it("can snapshot or record depending on the top level") {
            expect(view).to(self.performSnapshotAction())
        }
        it("can also pass in the action explicitly (here we use local reference to get rid of the self)") {
            expect(view).to(self.performSnapshotAction(snapshotAction))
        }
        context("But if some other suite was created") {
            let snapshotAction: NimbleSnapshotTestAction = .RecordSnapshot
            it("could reference a local snapshotAction") {
                expect(view).to(self.performSnapshotAction(snapshotAction))
            }
            context("and that reference could be as deep as") {
                it("wanted to be") {
                    expect(view).to(self.performSnapshotAction(snapshotAction))
                }
                it("could even make another one nested deeper") {
                    let snapshotAction: NimbleSnapshotTestAction = .HaveValidSnapshot
                    expect(view).to(self.performSnapshotAction(snapshotAction))
                }
                context("or") {
                    it("could just reference the one scoped above") {
                        let snapshotAction: NimbleSnapshotTestAction = snapshotAction
                        expect(view).to(self.performSnapshotAction(snapshotAction))
                    }
                }
            }
        }
    }
}
```

I hate the fact that you have to use `self` in these, but for me the benefit of being able to change record/checks across multiple tests with one line rather than many is enough to make me willing to sacrifice.

If this is something you think is cool and want to include feel free, I can also write tests and conform to better/different styles, but otherwise just feel free to close this issue!

Thanks again for the great glue between Swift+Nimble+FBSnaphotTestCase!

**Comment by ashfurrow** [comment]
That's pretty cool! Enums, protocol extensions, it checks off a lot of the "cool Swift features" list. Usually when this happens to me, I manually edit the [source file](https://github.com/ashfurrow/Nimble-Snapshots/blob/a9ec9a60b9e4ab08b5b0c9fe83ed7febdda368da/HaveValidSnapshot.swift#L166) to record instead 🙈 A more robust solution like this makes sense if that's happening often, but with [Snapshots Xcode Plugin](https://github.com/orta/snapshots) I've not had this experience. Do you reckon the workaround we have (editing the source to re-record all snapshots) is sufficient?

**Comment by tbondwilkinson** [comment]
Well editing the source is one way of going about it, but sometimes I'll still want to run other tests at the same time with checks not records, and I suppose I could be careful about my `fit` and `fdescribe` but I'm kinda careless and find that Quick sometimes is overzealous/nondeterministic about what it runs... So for me editing source is a not a replacement for this ad-hoc solution I've come up with.

Haven't used the plugin but just downloaded it :+1:!!

If were up to me it would be up to user preference whether to include this or not, but I have no sense of how to get in touch with other users... so I'll defer to you!

**Comment by ashfurrow** [comment]
I regularly replace all snapshots with no ill-effects. Since there identical files, git doesn't even recognize them as changed. 

Really appreciate the pull request, but I think I'd prefer to keep the existing solution. However, I think it definitely needs to be better documented or else no one can find it. Where did you go to look for this feature, and where do you think we should add documentation?

**Comment by tbondwilkinson** [comment]
That's fine with me!  It's strictly additive so I can keep my solution too ;) 

I looked around in the public interface for a way to switch behavior for an entire set of tests (a `describe` block) but found nothing.  I think just a little section in the README.md about what to do to rerun a bunch of tests at once would be appropriate!
