### ISSUE TITLE
Tests many sizes of view on one test

### ISSUE THREAD

**Issue by BrunoMazzo** [ashfurrow/Nimble-Snapshots#63]
Hi, I usually tests the layout of my view controllers taking snapshots on all the available sizes. Because of this I did a little wrapper to pass a array of sizes and test all on one call. I did not find a contribution guide to follow, so I would like to ask what do you thing of this feature? I can do a PR for evaluation.

**Comment by ashfurrow** [comment]
Very cool! When testing with available sizes, do you mean a `CGSize` size or a `UIContentSize` size class? We just recently added testing under content size classes, [check out the readme](https://github.com/ashfurrow/Nimble-Snapshots#dynamic-type). If you mean using snapshots of different sizes like `CGSize`, that sounds like a great feature, a pull request would be welcome.
