### ISSUE TITLE
Switch checks with records

### ISSUE THREAD

**Issue by MP0w** [ashfurrow/Nimble-Snapshots#66]
I was looking to add support for record mode and I saw `switchChecksWithRecords`, somehow it's undocumented and internal but apparently is always `false` inside the module.
I'm wondering if it is a mistake or you prefer it to be an hidden feature that also require to `@testable import Nimble_Snapshots` to use it.
If you are interested I can open a PR to make it public and document it.

**Comment by orta** [comment]
It's on purpose, we didn't feel it was a good API to have publicly, and so opted to allow people to change the source code to do that. I'd recommend you either use https://github.com/orta/Snapshots to do it properly, or improve https://github.com/orta/Snapshots-app if you want a Mac app version

**Comment by MP0w** [comment]
Thank you for the clarification! I was expecting a `recordMode` just because I used it in `FBSnapshotTestCase` but I will checkout your repos.
