### ISSUE TITLE
Any way to view difs on Xcode 8? 

### ISSUE THREAD

**Issue by kishykumar** [ashfurrow/Nimble-Snapshots#72]
Hi, 
Is there any way I can view the image difs? 
Also, which folder do the generated images go to?

I was using Xcode 7.3 and it had support for plugins. So, I was using the orta/Snapshots plugin to view the difs in Xcode itself. 
But now, Xcode 8.1 doesn't have plugin support. 

Any plan to add ksdiff support like https://github.com/facebook/ios-snapshot-test-case#features?

**Comment by orta** [comment]
we use ios-snapshots-test-case under to the  hood - so you'll get the exact same error messages from this library too!

However, IMO, you should convert my snapshots plugin into an App so that it works independent of the Xcode version 👍

**Comment by ashfurrow** [comment]
You can check out this app as well: https://github.com/Antondomashnev/FBSnapshotsViewer

Going to close this issue, let us know if we can clarify further 👍
