### ISSUE TITLE
Failure installing with Carthage

### ISSUE THREAD

**Issue by NachoSoto** [ashfurrow/Nimble-Snapshots#75]
```
carthage build Nimble-Snapshots --platform ios --toolchain com.apple.dt.toolchain.Swift_3_0_2
```

Fails with the error:
```
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

I understand this repo is trying to maintain compatibility with `Swift 2.3` and `Swift 3.0.x`, but unfortunately it looks like Xcode now enforces `SWIFT_VERSION` being set in each target :/

**Comment by ashfurrow** [comment]
I think it makes sense to drop 2.3 then. Thanks for opening the issue, I'll try to get to it asap but am travelling this week. Any PR would be appreciated of course :bow: but no pressure.

**Comment by NachoSoto** [comment]
No rush! I'll probably do this in the next few days then :)

**Comment by Lascorbe** [comment]
Can you exec it with `Swift_3_0_0` instead? (is the `SWIFT_VERSION` settled in the project). We can release another 2 minor versions with `3.0.1` and `3.0.2` tho.

There's no need to drop `Swift 2.3` (if we don't want to).

**Comment by NachoSoto** [comment]
I tried `3_0_0` too and it produces the same result.
My Cartfile has `github "ashfurrow/Nimble-Snapshots" ~> 4.4.2`

**Comment by ashfurrow** [comment]
Hey there, sorry for the radio silence on this. I was travelling last week but I'm back now. 

To be honest, I think it might be time to drop Swift 2.3 anyways, since Xcode is doing it. It's causing trouble here and there're lots of `#if` statements checking for Swift versions that we could remove. As long as we adhere to semantic versioning, I don't think this should be a problem. @Lascorbe anything I missed here?

**Comment by Lascorbe** [comment]
I think we're all good to drop Swift 2.3 🙂. I would just make it clear with a major release.

**Comment by marcelofabri** [comment]
@NachoSoto can you check if this is still a problem on `master`?

**Comment by fabiomassimo** [comment]
I added Nimble-Snapshots to my `Cartfile.private` (and also tried on `Cartfile`) but it got just ignored by `Carthage`. Not sure if this relates to this issue or I should open a new one.

My `Cartfile.private` looks like this

```
github "Quick/Nimble"
github "Quick/Quick"
github "facebook/ios-snapshot-test-case"
github "ashfurrow/Nimble-Snapshots"
```

Also tried:

```
$ carthage build Nimble-Snapshots
```

The output is just an empty `xcodebuild` run.

**Comment by fabiomassimo** [comment]
Sorry my bad, there was a conflict in my `Cartfile.resolved` due to `Nimble-Snapshots` built on an old version of Quick and Nimble.

I have compiled it locally with latest and greatest from Quick and Nimble and it works. Will it be worth a PR?

**Comment by ashfurrow** [comment]
Sure 👍

**Comment by fabiomassimo** [comment]
Cool: https://github.com/ashfurrow/Nimble-Snapshots/pull/91

It would be nice if someone can have a look on how we can port the implementation for new `XCTestObservationCenter` requirements. More details in the `Note` paragraph of the PR.

**Comment by marcelofabri** [comment]
I'm closing this since it should be fixed. Feel free to reopen if the issue persists!

**Comment by NachoSoto** [comment]
I'm back to testing this again, and now I'm getting a build failure:
```
swift:141:78: error: use of undeclared type 'Predicate'
                                         resizeMode: ResizeMode = .frame) -> Predicate<Snapshotable> {
                                                                             ^~~~~~~~~
/Users/nachosoto/dev/corsac/ios/Carthage/Checkouts/Nimble-Snapshots/HaveValidSnapshot.swift:224:86: error: use of undeclared type 'Predicate'
public func recordSnapshot(named name: String? = nil, usesDrawRect: Bool = false) -> Predicate<Snapshotable> {
                                                                                     ^~~~~~~~~
/Users/nachosoto/dev/corsac/ios/Carthage/Checkouts/Nimble-Snapshots/DynamicSize/DynamicSizeSnapshot.swift:203:75: error: use of undeclared type 'Predicate'
                                      resizeMode: ResizeMode = .frame) -> Predicate<Snapshotable> {
                                                                          ^~~~~~~~~
```

Cartfile.private:
```
github "Quick/Quick" ~> 1.1
github "Quick/Nimble" ~> 6.0.1
github "facebook/ios-snapshot-test-case" "2.1.4"
github "ashfurrow/Nimble-Snapshots"
```

Running:
```
carthage update Nimble-Snapshots --platform ios
```

**Comment by marcelofabri** [comment]
@NachoSoto `Nimble ~> 7.0` is required since `5.0.0` (I think)

**Comment by ashfurrow** [comment]
Sorry to hear that @NachoSoto – let's re-open this issue until we get things sorted out.

**Comment by NachoSoto** [comment]
@marcelofabri my bad, I missed that detail in the README. Testing with 7.0.

**Comment by NachoSoto** [comment]
That should be encoded in [the Cartfile](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/Cartfile#L1) so that it would have resulted in a dependency resolution error, instead of failing to compile with a confusing error :)

**Comment by marcelofabri** [comment]
@NachoSoto a PR would be very welcome 🙌 

I'm still a noob when it comes to Carthage, so sorry for all the trouble

**Comment by NachoSoto** [comment]
No worries! Thanks for the help. PR coming

**Comment by NachoSoto** [comment]
So now it builds, but my project is failing to build:
<img width="683" alt="screen shot 2017-07-03 at 1 41 31 pm" src="https://user-images.githubusercontent.com/685609/27807401-5ffd3c82-5ff5-11e7-9639-45daa00e6fff.png">

I'm confused: the file is there, and it's exported as "public" in the project, so not sure what's wrong.

**Comment by NachoSoto** [comment]
Never mind, rebuilding fixed that :)

**Comment by ashfurrow** [comment]
Okay, I've pushed a GitHub release to this repo, so you should be all set 👍 (I'm pushing a CocoaPods release too, for parity.) Let us know if that works, and thanks again for the issue.

**Comment by NachoSoto** [comment]
Awesome, everything's working great now :D super excited to finally be using this.

**Comment by ashfurrow** [comment]
Awesome! Let us know if you have questions 👍
