### ISSUE TITLE
Nimble Snapshot Crashing in beforeSuite

### ISSUE THREAD

**Issue by tapi** [ashfurrow/Nimble-Snapshots#76]
I'm working with a bit of legacy code that is configured, seemingly identically, in multiple places. 
Before refactoring each of these code paths to use a single method I thought Id create a reference snapshot with what should be the result and then compare each of the existing configure methods with the reference snapshot. 

It made sense to me to put the reference code in `beforeSuite`
I'm encountering a crash [here](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/HaveValidSnapshot.swift#L125) because of the force unwrapping of `currentExampleMetadata` which is set [here](https://github.com/ashfurrow/Nimble-Snapshots/blob/master/NimbleSnapshotsConfiguration.swift#L7). Quick has a `beforeSuite` configuration method but it doesn't have metaData to pass in.

I can think of a number of workarounds, I'm mostly raising the issue because not being able to use snapshots in `beforeSuite` was non-obvious and took a little digging to figure out why and wanted to see what other people thought.

**Comment by orta** [comment]
Sounds a bit weird to me TBH. 

You're running test matchers inside a scope that's not made for running tests, e.g. like in a describe block.

**Comment by ashfurrow** [comment]
Aye, I think we should probably avoid force-unwrapping in general though (stylistically). @tapi if the unwrap failed, what name should be used you reckon?

**Comment by tapi** [comment]
Im not sure, if its an error thats cool. But maybe a `guard let` with a fatal error would be warranted so as to provide context as to why.

**Comment by ashfurrow** [comment]
That makes sense to me – are you available for a pull request?

**Comment by tapi** [comment]
Cool, theres a few other force unwraps related to the same thing, want me to look at those as well?

**Comment by ashfurrow** [comment]
That sounds great! I'll leave them up to your discretion, happy to discuss anything too.

**Comment by tapi** [comment]
👍🏻 might have to wait a day or so.
