### ISSUE TITLE
Can't set custom reference dir

### ISSUE THREAD

**Issue by jgongo** [ashfurrow/Nimble-Snapshots#97]
While trying to set a custom reference dir I got the following error:
```
Could not infer reference image folder – You should provide a reference dir using FBSnapshotTest.setReferenceImagesDirectory(FB_REFERENCE_IMAGE_DIR)
```
This class is declared in `HaveValidSnapshot.swift` but is not declared public, so it seems you can't really use it. Is this intended behaviour? How can you set a custom reference directory?

**Comment by ashfurrow** [comment]
Yeah, sounds like a bug. Should be public. Would you be available to open a PR to fix it? Otherwise I can get to it this weekend.
