### ISSUE TITLE
Carthage doesn't have DynamicType or DynamicSize features

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Nimble-Snapshots#98]
Not sure how to fix this since subspecs are a feature of CocoaPods and not Carthage. Just always adding them would mean all users would be building OCMock, which they might not need. Not sure how to proceed.

**Comment by marcelofabri** [comment]
Note that DynamicSize doesn't need OCMock, so it could be included by default. I actually filled issues for both tasks (on mobile now, otherwise I'd link them)

**Comment by ashfurrow** [comment]
Great catch, thanks @marcelofabri I didn't realize these were tracked already in #89 and #90. I'll close 👍
